import "./globals.css";
import { Manrope } from "next/font/google";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} flex flex-col items-center min-h-screen`}
      >
        <div className="flex flex-col items-center w-full sm:w-[30rem] pt-8 px-12 text-center">
          <div className="font-bold text-5xl">
            Health<span className="text-brand">GPT</span>
          </div>
          <div className="text-xl">An AI-Powered Patient Diagnosis Tool</div>
          <div className="divider"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
